### ISSUE TITLE
HAproxy error after launch 

### ISSUE THREAD

**Issue by Issif** [naparuba/kunai#6]
after a ``kunai agent start``, I have this line in error logs : 

```
Cannot write path file /etc/haproxy/haproxy.cfg : [Errno 2] No such file or directory: u'/etc/haproxy/haproxy.cfg'
```
kunai starts well but stderr streams a lot of this.

For fixing it, I just removed *haproxy* tag in **/etc/kunai/local.json** and restart

**Comment by naparuba** [comment]
Fixed ^^
