### ISSUE TITLE
Don't show stats form disabled collectors

### ISSUE THREAD

**Issue by Issif** [naparuba/kunai#7]
With a ``kunai collectors show`` we have stats for disabled collectors even : 

```
========== [Collector apachestatus]:
{u'active': False,
 u'last_check': 1421414078,
 u'metrics': None,
 u'name': u'apachestatus',
 u'next_check': 1421414088,
 u'results': None}
========== [Collector nginx]:
{u'active': False,
 u'last_check': 1421414078,
 u'metrics': None,
 u'name': u'nginx',
 u'next_check': 1421414088,
 u'results': None}
```
These are useless, I think a ``kunai collectors show`` could show enabled collector only and a ``kunai collectors show all`` could all.

Other question :  Why have we **nginx** and **apachestatus** as names for their collectors? Just an **apache** is clearer IMHO.

**Comment by naparuba** [comment]
done.

call:

kunai collectors show --all to print all even disable one.
